### ISSUE TITLE
Support for non-ascii encodings?

### ISSUE THREAD

**Issue by ghost** [kristianlm/skypelog#1]
Thank you for a great project!

I have successfully unpacked my messages, or rather, all the latin ones. But  cyrillic ones do not appear in the output. Would it be very hard to add Russian support?

In particular, on line 
474                     fputc(Memory[Index],stdout);

this fputc only works with singular bytes (i.e., ascii), but the string is actually utf8.

**Comment by kristianlm** [comment]
Hi Lockywolf,

Gosh, I haven't looked this for ages. I didn't write any of it, I just repackaged some C code I found and put it on github. As such, I'm afraid that all I can do is help you guess specially without example input and output.

I see you've done some digging already. Are you getting truncated messages, or nothing? It seems to check for valid "printable" characters [just above](https://github.com/kristianlm/skypelog/blob/46afa68f1d464d396dc4420d20db6c116b6bf7cd/skypelog.c#L470) where you mention. I wonder what would happen if you remove the `> 0x03` condition. Perhaps your UTF8 chats contain such bytes.

Best of luck!

**Comment by ghost** [comment]
Yah, I already figured that out. The `isprintable` check in unnecessary, and `fputc` is only good for printing ascii, not unicode.

But today during lunch I have already bodged kinda a solution in c++, and actually prints utf8 well enough for my purposes.
 
I wouldn't like to make a pull request, because it would change the language from C to C++.

**Comment by kristianlm** [comment]
I'm glad you figured it out. 

Do you have a link for the C++ solution in case anyone else stumbles upon this here again? Thanks.

**Comment by ghost** [comment]
https://github.com/lockywolf/skypelog

**Comment by kristianlm** [comment]
Thank you. I Pulled it in, in the messies way possible, so people don't have to re-fix this. Thanks!
